name: CI/CD using Container Job

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Environment Variables
        env:
          RUNNER_TOKEN: ${{ secrets.TOKEN_SECRET }}
        run: echo "Environment variable RUNNER_TOKEN set"

      # - name: Deploy CI Container Job to Azure
      #   run: |
      #     az containerapp job create \
      #       --name ci-job \
      #       --resource-group altiushub-test \
      #       --environment Self-Hosted-Runner \
      #       --image altiushub.azurecr.io/container-ci-job:latest \
      #       --max-executions 1 \
      #       --env-vars GITHUB_REPO=https://github.com/RathodSaiGiridharPrasad/pipeline-exercise

            