# .github/workflows/common.yml
name: Common Workflow

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ inputs.service-name }}
      ENVIRONMENT: ${{ inputs.environment }}
      VERSION: ${{ inputs.version }}
    steps:
      - name: Print environment variables
        run: |
          echo "Service: $SERVICE_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Version: $VERSION"
