name: CI/CD for Main Branch

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Increment version
      run: |
        chmod +x ./increment_version.sh
        ./increment_version.sh app-frontend-tests-test ${{ github.head_ref }} ${{ github.sha }}