name: Increment Version on Merge to Staging
 
on:
  pull_request:
    types:
      - closed
    branches:
      - staging
 
jobs:
  increment-version:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Increment Version
        run: |
          # Your script to increment the version here
          echo "Incrementing version for PR merged from 'dev' to 'staging'"