name: App Orchestration Rollout

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      version:
        description: "Global version tag"
        required: true
        default: "1.0.0"

permissions:
  id-token: write
  contents: read

jobs:
  rollout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Orchestration Repo
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Set Environment Variable VERSION
      run: |
        echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

    - name: Show VERSION
      run: echo "Environment variable VERSION set to $VERSION"